import type { UserProfile } from '../src/models';

export interface Scenario {
  id: string;
  description: string;
  profile: UserProfile;
}

export function findScenario(id: string): Scenario {
  const sc = SCENARIOS.find((s) => s.id === id);
  if (!sc) throw new Error(`Unknown scenario: ${id}`);
  return sc;
}

export const SCENARIOS: Scenario[] = [
  {
    id: 'S001',
    description: '사회초년생 직장인 — 연금저축·ISA 미보유',
    profile: {
      age: 26,
      annual_salary: 3600,
      income_type: 'employee',
      invest_types: ['domestic_stock', 'etf_domestic'],
      monthly_invest: 30,
      has_isa: false,
      has_pension: false,
      has_irp: false,
      pension_contribution: 0,
      irp_contribution: 0,
      financial_income: 10,
      risk_tolerance: 'medium',
      has_spouse: false,
      has_children: false,
      has_minor_children: false,
      foreign_stock_unrealized_profit: 0,
      dividend_income: 5,
      holds_high_dividend: false,
    },
  },
  {
    id: 'S002',
    description: '중간 소득 직장인 — 연금저축 부분납입 + 미국주식 수익 大',
    profile: {
      age: 35,
      annual_salary: 6000,
      income_type: 'employee',
      invest_types: ['foreign_stock', 'etf_foreign', 'domestic_stock'],
      monthly_invest: 100,
      has_isa: false,
      has_pension: true,
      has_irp: false,
      pension_contribution: 300,
      irp_contribution: 0,
      financial_income: 80,
      risk_tolerance: 'high',
      has_spouse: true,
      has_children: true,
      has_minor_children: true,
      foreign_stock_unrealized_profit: 1500,
      dividend_income: 30,
      holds_high_dividend: false,
    },
  },
  {
    id: 'S003',
    description: '고소득 직장인 — 연금저축+IRP 풀납입, 금융소득 종합과세 접근',
    profile: {
      age: 45,
      annual_salary: 12000,
      income_type: 'employee',
      invest_types: ['foreign_stock', 'fund', 'bond', 'reit'],
      monthly_invest: 200,
      has_isa: true,
      has_pension: true,
      has_irp: true,
      pension_contribution: 600,
      irp_contribution: 300,
      financial_income: 1800,
      risk_tolerance: 'medium',
      has_spouse: true,
      has_children: true,
      has_minor_children: false,
      foreign_stock_unrealized_profit: 3000,
      dividend_income: 800,
      holds_high_dividend: true,
    },
  },
  {
    id: 'S004',
    description: '프리랜서 — ISA만 보유, 해외주식 중간 수익',
    profile: {
      age: 32,
      annual_salary: 5000,
      income_type: 'freelancer',
      invest_types: ['domestic_stock', 'foreign_stock', 'fund'],
      monthly_invest: 50,
      has_isa: true,
      has_pension: false,
      has_irp: false,
      pension_contribution: 0,
      irp_contribution: 0,
      financial_income: 30,
      risk_tolerance: 'medium',
      has_spouse: false,
      has_children: false,
      has_minor_children: false,
      foreign_stock_unrealized_profit: 500,
      dividend_income: 15,
      holds_high_dividend: false,
    },
  },
  {
    id: 'S005',
    description: '50대 직장인 — 금융소득 종합과세 경계, 고배당주 보유',
    profile: {
      age: 53,
      annual_salary: 10000,
      income_type: 'employee',
      invest_types: ['bond', 'reit', 'deposit', 'etf_foreign', 'domestic_stock'],
      monthly_invest: 150,
      has_isa: false,
      has_pension: true,
      has_irp: true,
      pension_contribution: 600,
      irp_contribution: 300,
      financial_income: 1900,
      risk_tolerance: 'low',
      has_spouse: true,
      has_children: true,
      has_minor_children: false,
      foreign_stock_unrealized_profit: 800,
      dividend_income: 1200,
      holds_high_dividend: true,
    },
  },
  {
    id: 'S006',
    description: '무소득 전업주부 — 해외주식 미실현 수익 큰 상태',
    profile: {
      age: 38,
      annual_salary: 0,
      income_type: 'none',
      invest_types: ['foreign_stock', 'etf_foreign'],
      monthly_invest: 50,
      has_isa: false,
      has_pension: false,
      has_irp: false,
      pension_contribution: 0,
      irp_contribution: 0,
      financial_income: 50,
      risk_tolerance: 'high',
      has_spouse: true,
      has_children: true,
      has_minor_children: true,
      foreign_stock_unrealized_profit: 2000,
      dividend_income: 20,
      holds_high_dividend: false,
    },
  },
  {
    id: 'S007',
    description: '서민형 ISA 대상 저소득 직장인',
    profile: {
      age: 29,
      annual_salary: 3000,
      income_type: 'employee',
      invest_types: ['deposit', 'domestic_stock'],
      monthly_invest: 20,
      has_isa: false,
      has_pension: false,
      has_irp: false,
      pension_contribution: 0,
      irp_contribution: 0,
      financial_income: 5,
      risk_tolerance: 'low',
      has_spouse: false,
      has_children: false,
      has_minor_children: false,
      foreign_stock_unrealized_profit: 0,
      dividend_income: 2,
      holds_high_dividend: false,
    },
  },
  {
    id: 'S008',
    description: '고소득 프리랜서 — 금융소득 종합과세자, 고배당 포트폴리오',
    profile: {
      age: 44,
      annual_salary: 8000,
      income_type: 'freelancer',
      invest_types: ['foreign_stock', 'reit', 'bond', 'etf_domestic'],
      monthly_invest: 150,
      has_isa: false,
      has_pension: true,
      has_irp: false,
      pension_contribution: 400,
      irp_contribution: 0,
      financial_income: 2500,
      risk_tolerance: 'medium',
      has_spouse: true,
      has_children: true,
      has_minor_children: false,
      foreign_stock_unrealized_profit: 1200,
      dividend_income: 1800,
      holds_high_dividend: true,
    },
  },
  {
    id: 'S009',
    description: '30대 맞벌이 — 미국주식 수익 크고 배우자 증여 고려',
    profile: {
      age: 37,
      annual_salary: 7000,
      income_type: 'employee',
      invest_types: ['foreign_stock', 'etf_foreign'],
      monthly_invest: 120,
      has_isa: false,
      has_pension: true,
      has_irp: true,
      pension_contribution: 600,
      irp_contribution: 300,
      financial_income: 120,
      risk_tolerance: 'high',
      has_spouse: true,
      has_children: false,
      has_minor_children: false,
      foreign_stock_unrealized_profit: 4000,
      dividend_income: 50,
      holds_high_dividend: false,
    },
  },
  {
    id: 'S010',
    description: '40대 — ETF 혼합 보유, 세금 구조 최적화 필요',
    profile: {
      age: 42,
      annual_salary: 8000,
      income_type: 'employee',
      invest_types: ['etf_domestic', 'etf_foreign', 'fund'],
      monthly_invest: 80,
      has_isa: false,
      has_pension: true,
      has_irp: false,
      pension_contribution: 400,
      irp_contribution: 0,
      financial_income: 200,
      risk_tolerance: 'medium',
      has_spouse: true,
      has_children: true,
      has_minor_children: false,
      foreign_stock_unrealized_profit: 0,
      dividend_income: 100,
      holds_high_dividend: false,
    },
  },
  {
    id: 'S011',
    description: '금융소득 종합과세자 — 고배당 분리과세 최대 활용',
    profile: {
      age: 55,
      annual_salary: 15000,
      income_type: 'employee',
      invest_types: ['domestic_stock', 'reit', 'bond'],
      monthly_invest: 300,
      has_isa: true,
      has_pension: true,
      has_irp: true,
      pension_contribution: 600,
      irp_contribution: 300,
      financial_income: 3500,
      risk_tolerance: 'low',
      has_spouse: true,
      has_children: true,
      has_minor_children: false,
      foreign_stock_unrealized_profit: 0,
      dividend_income: 2800,
      holds_high_dividend: true,
    },
  },
  {
    id: 'S012',
    description: '미성년 자녀 보유 — 자녀 주식 증여 절세 계획',
    profile: {
      age: 40,
      annual_salary: 9000,
      income_type: 'employee',
      invest_types: ['foreign_stock', 'domestic_stock'],
      monthly_invest: 100,
      has_isa: true,
      has_pension: true,
      has_irp: true,
      pension_contribution: 600,
      irp_contribution: 300,
      financial_income: 150,
      risk_tolerance: 'medium',
      has_spouse: true,
      has_children: true,
      has_minor_children: true,
      foreign_stock_unrealized_profit: 2500,
      dividend_income: 80,
      holds_high_dividend: false,
    },
  },
];
